// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvG60-EgsgWMgYQV5cuIAbY1eWkJ_5lE',
    appId: '1:12237192524:web:bb91be278b943d1e0fe3e9',
    messagingSenderId: '12237192524',
    projectId: 'marvelapp-a1f05',
    authDomain: 'marvelapp-a1f05.firebaseapp.com',
    storageBucket: 'marvelapp-a1f05.appspot.com',
    measurementId: 'G-RN7729YDLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa9Pm8j6EljRVRjOp_DGvtC8u_bKt6oCI',
    appId: '1:12237192524:android:b86654360144cf300fe3e9',
    messagingSenderId: '12237192524',
    projectId: 'marvelapp-a1f05',
    storageBucket: 'marvelapp-a1f05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChnEUvcSiBE1U9DrYGOp4QhtPtSCiOTyo',
    appId: '1:12237192524:ios:044f7690b335dfc60fe3e9',
    messagingSenderId: '12237192524',
    projectId: 'marvelapp-a1f05',
    storageBucket: 'marvelapp-a1f05.appspot.com',
    iosClientId: '12237192524-kua3nv6h8i1cqef0ce6s7jnmpv62ims2.apps.googleusercontent.com',
    iosBundleId: 'com.cyberdine.marvelapp',
  );
}
